services:
  rag-api:
    build: .
    container_name: ai-rag-knowledge-assistant
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped